# Robot arm configuration

# Link names
link_names: ["base", "shoulder", "elbow", "wrist_1", "wrist_2", "wrist_3"]

# Links maximum speeds
# maximum angular speeds in radians per second
link_max_speeds: [2.0944, 2.0944, 3.1416, 3.1416, 3.1416, 3.1416]

# Links initial position
# joint angles in radians in the range [-pi, pi)
link_initial: [0, 0, 0, 0, 0, 0]

# Denavit-Hartenberg parameters for each link
# theta (z angle), d (z translation), a (x translation), alpha (x angle)
dh_links: [[0, 0.118, 0, 1.5708],
           [0, 0, -0.6127, 0],
           [0, 0, -0.5716, 0],
           [0, 0.1639, 0, 1.5708],
           [0, 0.1157, 0, -1.5708],
           [0, 0.0922, 0, 0]]
           
