# theta (z angle), d (z translation), a (x translation), alpha (x angle)
dh_links: [[0, 0.118, 0, 1.5708],
           [0, 0, -0.6127, 0],
           [0, 0, -0.5716, 0],
           [0, 0.1639, 0, 1.5708],
           [0, 0.1157, 0, -1.5708],
           [0, 0.0922, 0, 0]]
           
